### ISSUE TITLE
Crash with Nemesis System

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#1]
Forge v14.23.5.2810-1.12.2
[Nemesis System](https://minecraft.curseforge.com/projects/nemesis-system) v2
[Living Ench](https://minecraft.curseforge.com/projects/living-enchantment) v3.1.6
Apotheosis v1.2.0

I got this crash after opening the bonus chest that had a Living Enchantment book in it. The crash seems to be related to the Nemesis mod.
[Crash Report](https://paste.dimdev.org/iwanicilil.mccrash)

**Comment by Shadows-of-Fire** [comment]
Interesting, would you be able to check your `config/apotheosis/enchantments.cfg` file to see if the Living enchantment has an entry there?  If it doesnt, it's being registered late, and should be considered a bug in that mod.

I could fix it on my end by initializing the entries later, but i'd like to figure out what's happening first.

**Comment by WenXin20** [comment]
Yes, its listed there.

**Comment by Shadows-of-Fire** [comment]
Ah, then I suppose it's a different enchantment.  Tracking such a thing would be rather difficult, so I guess i'll just try to load the config later.

**Comment by WenXin20** [comment]
Thanks for looking into it. Does it have anything to do with the Nemesis System mod?

**Comment by WenXin20** [comment]
I also have Quark Oddities, which changes the enchanting system. Could that be it? Is was also wondering if it has compatibility with this mod.

**Comment by Shadows-of-Fire** [comment]
No, it's strictly something registering an enchantment after I load my configs, which are used to override min/max levels of enchantments.  All enchantments should already be registered at this time, so it's a strange issue.

**Comment by Laike-Endaril** [comment]
Looks like "info" is null on this line:
[https://github.com/Shadows-of-Fire/Apotheosis/blob/c5504b2e3623410ff0995fd1ef47341e7f1decf7/src/main/java/shadows/ench/EnchModule.java#L327](https://github.com/Shadows-of-Fire/Apotheosis/blob/c5504b2e3623410ff0995fd1ef47341e7f1decf7/src/main/java/shadows/ench/EnchModule.java#L327)

I didn't look into it any further.  Not sure if a simple null check + cancel will work here or if that should never be null.

Was just taking a quick look at this since I was already here due to the other issue on the tracker, and you only had 2 issues.

**Comment by Shadows-of-Fire** [comment]
It should never be null.  I'm going to lazy init enchantments that do return null, but it will log an error message blaming the mod not following proper registration practices.

**Comment by Laike-Endaril** [comment]
:+1:
