### ISSUE TITLE
Underlying Exception:  java.lang.RuntimeException: Unknown element name:spellbook

### ISSUE THREAD

**Issue by Willem07** [Shadows-of-Fire/Apotheosis#1028]
Errors with the Iron's Spells 'n Spellbooks mod

Apotheosis-1.20.1-7.0.5
ApothicAttributes-1.20.1-1.1.4
Placebo-1.20.1-8.3.7

irons_spellbooks-1.20.1-2.0.0

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/12774975/latest.log)

**Comment by SiverDX** [comment]
this is caused by irons spellbooks and their apotheosis compat
their datapack files are still active but code-wise its deactivated: https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.20.1/src/main/java/io/redspace/ironsspellbooks/compat/apotheosis/ApotheosisHandler.java

you will need to ask them to activate the code part or remove the datapack files

**Comment by Willem07** [comment]
irons_spellbooks-1.20.1-2.0.0
and
Apotheosis-1.20.1-7.0.5
not compatible

need to update the **_datapack irons_spellbooks-1.20.1-2.0.0.jar\assets\apotheosis_**
