### ISSUE TITLE
Incompatible with AdventureZ (Through Connector)

### ISSUE THREAD

**Issue by SlayDigger** [Shadows-of-Fire/Apotheosis#1106]
I've reported this issue to Connector and was told that its an issue that they can't resolve, and I'd have to track down the devs of either mod and ask for some support. So basically, upon trying to launch the game with both Apotheosis & AdventureZ (Through Connector) The game crashes with this as the log: https://gist.github.com/SlayDigger/c7583969851dad671a4fd6b26a3b37a2
The issue as the connector dev described it is [here](https://github.com/Sinytra/Connector/issues/526)

**Comment by Shadows-of-Fire** [comment]
Yeah I don't think I can do anything about this, the issue comes from the coremod overriding the target that their mixin is looking for, and the coremod always runs first.

So what has to happen is (a) their mixin needs to be aware of my replacement and (b) whatever manipulation they are doing to max levels needs to be compatible with my changes.

(A) is possible, but (B) not so much since the mods are on different platforms.

**Comment by ajaxnotmeta** [comment]
> Yeah I don't think I can do anything about this, the issue comes from the coremod overriding the target that their mixin is looking for, and the coremod always runs first.
> 
> So what has to happen is (a) their mixin needs to be aware of my replacement and (b) whatever manipulation they are doing to max levels needs to be compatible with my changes.
> 
> (A) is possible, but (B) not so much since the mods are on different platforms.

so the only possible help was asking AdventureZ devs if they hapen to willing for support(if its even possible) right?
