### ISSUE TITLE
Clients Unable to Join Dedicated Server with Randomium

### ISSUE THREAD

**Issue by BookerCatch** [Shadows-of-Fire/Apotheosis#1110]
With Apotheosis, Randomium, and both mods' dependencies loaded, the client is unable to join a dedicated server. Client will get stuck on the login screen unable to join, and then the launcher will freeze as the logs get spammed indefinitely. Please see debug and latest logs attached below. Unsure which of the two is the culprit, but I thought it prudent to bring it to your attention. 

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13753862/latest.log)
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13753863/debug.log)

https://github.com/MehVahdJukaar/Randomium/issues/27

**Comment by Shadows-of-Fire** [comment]
This appears to be caused by randomium invoking generation of creative tabs exceptionally early, causing the search tree to load, and causing tooltips to be generated (to populate the search tree).  Randomium needs to make their event handler run later (probably in a `ServerStartedEvent` or similar).
