### ISSUE TITLE
[1.20.1] Can't remove Rogue Spawners with datapacks

### ISSUE THREAD

**Issue by DaddySpin** [Shadows-of-Fire/Apotheosis#1175]
I'm trying to remove Rogue Spawners from generating but the game just crashes when creating a new world.

![Code_23wAztRaYW](https://github.com/Shadows-of-Fire/Apotheosis/assets/34575655/9a996ef7-940d-4212-b06b-74d7c6e78627)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/14322992/latest.log)

**Comment by SiverDX** [comment]
that is invalid syntax

[https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/worldgen/configured_feature/rogue_spawner.json / ](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/worldgen/placed_feature/rogue_spawner.json)

https://docs.minecraftforge.net/en/latest/resources/server/conditional/

Also why not just use `WorldgenEvents` since you're using KubeJS

**Comment by FooterManDev** [comment]
~~WorldgenEvents is disabled in KubeJS on 1.20.~~
Edit: It appears they have fixed the worldgen issues, I am mistaken.
