### ISSUE TITLE
Chainsaw enchant

### ISSUE THREAD

**Issue by bigtruckin78** [Shadows-of-Fire/Apotheosis#1189]
Would it be possible to add paxels to be compatible with the Chainsaw enchantment?

**Comment by Shadows-of-Fire** [comment]
It should work as-is (the logic queries if the target item can perform the `AXE_DIG` tool action, which is the accepted way of querying an axe).  If it does not, it may be because the item is NBT-sensitive on being a paxel, which could prevent the application.  I can add a check that is nbt-sensitive instead, but it will still not work if the paxel is not reporting that it can perform the action.
