### ISSUE TITLE
Affixes in Reforging Table Preview Do Not Match Outcome

### ISSUE THREAD

**Issue by thegreywulfe** [Shadows-of-Fire/Apotheosis#1201]
This appears to be a duplicate of  #1145 but in the current version (7.3.3).

![Untitled1](https://github.com/Shadows-of-Fire/Apotheosis/assets/52047121/6695a08e-6d36-4919-b434-48ea03218ae6)
![Untitled2](https://github.com/Shadows-of-Fire/Apotheosis/assets/52047121/f1c7449f-3f4b-43ac-8f86-d79e9c0a73d5)

Screenshots are simplistic and using lower level rarity materials mostly because I'm hurting for mats after doing a bunch of testing, but I promise that it's the same issue that can be seen in other posts. Fully different outcomes vs. the expected.

Items do not reforge as expected from the preview in the reforging table. As with other instances of this bug, the issue does not replicate in singleplayer, and only appears in a dedicated multiplayer server.

For me this is appearing in a friend's server that is modded to hell, which may very well be the source of the issue. Minecraft version is 1.20.1, modlist can be found here:
[All Mods.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14609009/All.Mods.txt)

It's likely this is a weird edge case related to config files and UI mods or something to that effect. If I knew what the fix was back in 7.3.0 I might be able to fix something on my end.

**Comment by Eduardo-Fittipaldi** [comment]
I confirm the same issue is happening in my server, Forge Version 47.2.19, Mod version 7.3.3.

**Comment by Shadows-of-Fire** [comment]
Nothing has changed relating to reforging since the original fix, nor can I reproduce any issues with reforging in a dedicated server environment on stock settings.

Given the affix names, what is happening here is that your client thinks that Axe is a `SWORD` class object, instead of a `HEAVY_WEAPON` class object.  If you have overrides in the config, that config file must match from client to server; if there isn't a mismatch (or this object is not being overridden), then it's probably just tetra being weird and there isn't anything I can do about it.
