### ISSUE TITLE
[Bug] Incompatible with mod "Golden Age Combat"

### ISSUE THREAD

**Issue by Naireem-sudo** [Shadows-of-Fire/Apotheosis#1227]
Apotheosis overrides the enchantment "Sharpness" and Golden Age Combat too. It will ignore the "Boost Sharpness Enchant" from Golden Age Combat (from 0.5 dmg to 1.25 dmg increase).

**Comment by Shadows-of-Fire** [comment]
This is because Apoth is also rebalancing sharpness (and the other bane enchantments) to accommodate Apoth making Sharpness compatible with a single bane enchantment.  These rebalancings can never implicitly be compatible with one another.  Golden Age Combat should be able to apply whatever mixin they are applying to the vanilla enchantment class to mine to achieve a similar result.

https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/java/dev/shadowsoffire/apotheosis/ench/replacements/BaneEnchant.java
