### ISSUE TITLE
Problem with the gems (item.apotheosis.gem)

### ISSUE THREAD

**Issue by Cardavidev** [Shadows-of-Fire/Apotheosis#1260]
Every gem I get in from the mod turns into a bugged one, because before it comes to mi inventory it looks normal
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/142436671/53aa48ab-fae3-45d5-ae6b-36fabd5c77c5)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/142436671/0560cec9-ef61-41ac-817a-eecb117e65a8)

**Comment by Shadows-of-Fire** [comment]
If you hold the gem and execute `/placebo hand` what is the output?

**Comment by deretos239** [comment]
> If you hold the gem and execute `/placebo hand` what is the output?

Hi, just got the same issue where. Here's the output of the "/placebo hand":
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/35036386/88c51923-8887-43f2-b98a-2887efe99612)

**Comment by deretos239** [comment]
Update on the above: 
Checked the "skilltree:citrine_0", and here's what I found: 
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/35036386/55cd4857-1ff8-41cc-a84f-1b713a516bd6)

It looks like the Passive Skill Tree overrides the Apotheosis with the code, making some drops (or all of them) to the Crushed Citrine, which does nothing, making an error. In my case, that's all the drops from mining, but others seem to have issues with even gems in wildness.

**Comment by Shadows-of-Fire** [comment]
The issue reported by the @Cardavidev is probably different, since it seems to be a breach gem going invalid.  I have been notified that `Mo' Enchantments` is nuking the nbt data off of random items, so that's probably the culprit there.

As for the issue you're seeing @deretos239, you may need to report that to passive skill tree. I suspect those gems should not be generating (based on their own error message).

**Comment by deretos239** [comment]
@Shadows-of-Fire Sure thing, will do. Thanks for your swift reply and cooperation! Will try to fix that. :D 
(can that be fixed by modifying the priorities in mods, in which they should be loaded/generated/overridden by each other? Sorry, I'm far from being known with code or minecraft modding, just a thought)

And, uhh.. I'm new to the github, how do I create such a topic like this one?

**Comment by Shadows-of-Fire** [comment]
The repo for PST is here https://github.com/Daripher/Passive-Skill-Tree
