### ISSUE TITLE
Ticking Entites when updated to latest version of mod (1.20.1)

### ISSUE THREAD

**Issue by GhostLupine** [Shadows-of-Fire/Apotheosis#1298]
So, I'm trying to make a mod pack, and saw that this mod has an update and it seemed cool, however, ever since I updated it, I would get notifications that there are ticking entities from Neruina mod, which I never had these notifications pop up until I updated this mod and the other dependencies for this mod. Here is the crash report here, which I assume will be helpful to show what's wrong. Again, I have not had issues with ticking entities, until I updated this mod. It may be conflicting with my other mods, but I'm not sure, because I don't know how to really read a crash log and know what to look for. However, I will try to look through and see what mod might be causing a confliction and report it. To be more specific, the Apotheosis mod version I'm speaking about is 7.4.0 for Minecraft version 1.20.1
[crash-2024-07-15_21.57.01-client.txt](https://github.com/user-attachments/files/16242682/crash-2024-07-15_21.57.01-client.txt)

**Comment by meeprdib** [comment]
Loot beams is incompatible with latest Apotheosis.

**Comment by meeprdib** [comment]
Some advice about reading crash logs / diagnosing issues though; what you want to find in the logs is a "stacktrace", as that's where most issues are detailed. In the crash report you sent, there's a snippet reading as follows.

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	LootBeams (lootbeams), Version: 1.20.1
		at TRANSFORMER/lootbeams@1.20.1/com.lootbeams.compat.ApotheosisCompat.isApotheosisItem(ApotheosisCompat.java:33)
Stacktrace:
	at com.lootbeams.compat.ApotheosisCompat.isApotheosisItem(ApotheosisCompat.java:33) ~[lootbeams-1.20.1-1.2.5.jar%23524!/:1.20.1-1.2.5] {re:classloading}
	at com.lootbeams.LootBeamRenderer.compatRarityCheck(LootBeamRenderer.java:174) ~[lootbeams-1.20.1-1.2.5.jar%23524!/:1.20.1-1.2.5] {re:classloading}
	at com.lootbeams.ClientSetup.overrideLight(ClientSetup.java:229) ~[lootbeams-1.20.1-1.2.5.jar%23524!/:1.20.1-1.2.5] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.EntityRenderer.localvar$zjd000$render(EntityRenderer.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23624!/:?]
```

Ignoring the suspected mod being named directly in that snippet, you can see that something with "lootbeams.compat.ApotheosisCompat" is acting up. Sometimes it's more or less obvious what the issue is, but it's generally good advice to look for "stacktrace" when trying to figure out where something went wrong. You may also need to look in your latest.log file to see if there's any information that may have been missed in the crash report.

Also, if you're interested, there's a version of loot beams in the Apotheosis discord that's compatible with latest Apotheosis.

**Comment by GhostLupine** [comment]
Sorry just took a look here just now. Thank you for the advice, and I will try out this version of loot beams. Thanks again.
