### ISSUE TITLE
Difficulty Compiling

### ISSUE THREAD

**Issue by ItzLeTurtle** [Shadows-of-Fire/Apotheosis#1302]
Might just be a skill issue but when I compile with gradlew build the mod causes a crash inside my world.  The version on curseforge works fine but when I try to compile it myself, upon opening any inventory in the world it crashes with the following error:

"The game crashed whilst rendering screen
Error: java.lang.ClassCastException: class net.minecraft.world.level.block.RotatedPillarBlock cannot be cast to class dev.shadowsoffire.apotheosis.ench.api.IEnchantingBlock (net.minecraft.world.level.block.RotatedPillarBlock is in module minecraft@1.20.1 of loader 'TRANSFORMER' @25131637; dev.shadowsoffire.apotheosis.ench.api.IEnchantingBlock is in module apotheosis@7.4.0 of loader 'TRANSFORMER' @25131637)

The manually compiled file size is a few hundred kb smaller so it is definitely different.  Any suggestions on how to build it successfully?

Thanks for all your work on this mod, it really is one of the best ones out there.

**Comment by Shadows-of-Fire** [comment]
The last commit (after the release) was a PNG optimization pass, so I expect newly-compiled jars to be smaller than the prior 7.4.0 release.  For me, a fresh jar (with a minimal local change) is 2,595 KB.

You shouldn't need to perform any actions other than `gradlew build` to create the mod.  The crash you're receiving (though, there might be a different crash, since you have not provided the full crash log) indicates that the `BlockMixin` has failed to apply, which would only occur if the `apotheosis.mixins.json` file is absent from the built jar.

You should first provide the full debug.log file from your crashing production launch, and we can work from there.

**Comment by ItzLeTurtle** [comment]
Apologies, I was almost certain it was an issue on my end building.  Here is the crash log. Didn't realize how big these things are:

https://file.io/k41cRsKtZTTo

I'm playing on 1.20.1 with quark along with a ton of other mods.  Just working on balancing right now.

**Comment by Shadows-of-Fire** [comment]
5a79de2646cc9b76927fe965598ab49c89b770f0
