### ISSUE TITLE
Similar Mixin-Crash Due to Trims (BetterTrims)

### ISSUE THREAD

**Issue by bkoee** [Shadows-of-Fire/Apotheosis#1352]
I found https://github.com/Shadows-of-Fire/Apotheosis/issues/1301#issue-2421441306 but for BetterTrims https://github.com/Bawnorton/BetterTrims

Which I think is open source?

relevant line from crash (I think): "EnchantmentHelperMixin from mod bettertrims -> Prepare Injections ->"

I can provide more if needed but the mods I am running make the logs quite unbearable.

For now I will be foregoing BetterTrims (your mod is way more worth it)

**Comment by Shadows-of-Fire** [comment]
Yeah there's a similar issue there.  Doesn't appear to exist in their 1.21 branch though (the relevant mixin no longer exists) and I don't know if they have any plans to update 1.20 (Apoth is already done with 1.20 development as well).  

The best fix here would be for them to make [this mixin](https://github.com/Bawnorton/BetterTrims/blob/main/src/main/java/com/bawnorton/bettertrims/mixin/compat/connector/forge/EnchantmentHelperMixin.java) also conditional on apotheosis (since it seems they already have some form of conditional mixins setup?).

**Comment by bkoee** [comment]
Ok ty for the info shadow! I would've updated the server to 1.21 but create is holding me back :(
