### ISSUE TITLE
Advanced Netherite Mod issue when reforging

### ISSUE THREAD

**Issue by icha-senpai** [Shadows-of-Fire/Apotheosis#1355]
the base version of the advanced netherite swords work with higher enchants when not reforged but when i reforge it in the table the enchants seem to no longer work 

not really sure what the issue is

**Comment by icha-senpai** [comment]
i noticed it more with sweeping edge enchant at my enderman farm

if you want a video showing it more clearly let me know i'll make one

**Comment by Shadows-of-Fire** [comment]
Affixes don't interact with enchantments, nor do they have special handling for different mods' items (so there is no way for an affix to behave differently on items from Advanced Netherite as compared to any others).  If you can perform a root cause of this issue, feel free to reopen it, but there isn't anything for me to fix here.
