### ISSUE TITLE
Easy Anvils are incompatible with apotheosis.

### ISSUE THREAD

**Issue by Cosmoros-git** [Shadows-of-Fire/Apotheosis#1369]
Because of this mod overrides Anvils functionality, Easy Anvils does not provide any functionality the mod adds. 

The enchanting part should stay the same, but formatting, keeping items on visuals, etc, should be left in.

**Comment by meeprdib** [comment]
Yeah, I think that Apotheosis should yield to other mods overriding the anvil level cap mixin, or remove it entirely due to mod incompatibilities.

**Comment by SiverDX** [comment]
compared to other mods it's actually pretty important due to higher enchantment levels scaling experience costs way above the vanilla anvil limit far quicker

the anvil block (entity) part is needed for gameplay reasons (gem dust and splitting enchantment books, might be more not sure)

at a certain point things just aren't meant to be compatible
(unless someone makes an additional, dedicated compat. mod - because probably neither of the mods would want the other as a dependency in their proejct)

**Comment by Cosmoros-git** [comment]
Maybe then add formatting and display functionality? At least the formatting would be neat.

**Comment by Shadows-of-Fire** [comment]
Easy Anvils is incompatible with the changes made for the enchanting module, there's no way to rectify that.  The whole "anvils being enchantable" thing was dropped in 1.21 though, so I guess it might work there.
