### ISSUE TITLE
[Question] How do I prohibit items that already have affixes to be reforged?

### ISSUE THREAD

**Issue by min0-5hadowsong** [Shadows-of-Fire/Apotheosis#1389]
How do I prohibit items that already have **affixes** to be **reforged**? I did not find configs. My apotheosis version is **7.4.2**.

**Comment by meeprdib** [comment]
Disabling affixed items from being able to be reforged again is not a feature in the mod.

**Comment by min0-5hadowsong** [comment]
> Disabling affixed items from being able to be reforged again is not a feature in the mod.

Thank you for your response. Can I achieve this functionality through other mods, such as KubeJS?

**Comment by meeprdib** [comment]
Would be a better question to ask KubeJS discord

**Comment by min0-5hadowsong** [comment]
> Would be a better question to ask KubeJS discord

Thanks for your suggestion.

**Comment by Shadows-of-Fire** [comment]
This is not possible under the current implementation of the reforging table. I'm not really inclined to make it possible, either. It's not beneficial from a game design perspective to force users to craft a new item just to reforge again, since the materials tend to be very replenishable and the reforge results do not change per-item.

You would encourage the users to reforge wooden items of the same category until they see the results they want, then reforge the item they really wanted to reforge, which solves nothing.
