### ISSUE TITLE
[1.16.3] mod conflict

### ISSUE THREAD

**Issue by Bass2style** [Shadows-of-Fire/Apotheosis#232]
Hi,

Apotheosis seems conflicting with MoreVanillaLib (lib for Vanilla Hammers).
the game is crashing when loading, and the debug log seems to say that's Apotheosis fault, that says that an issue with planks is occured.

i try to find the log back, because i tryed without MoreVanillaLib (and Hammers), and it's running now. (not correctly, but that can come from another mod actually.)

**Comment by Shadows-of-Fire** [comment]
The way that apotheosis tries to categorize tools for use with the name system is incompatible with some bad programming practices that more vanilla lib employs, namely static init of ingredients in this class: https://github.com/MelanX/MoreVanillaLib/blob/6f536b77250dfe1292d5bbb1a82b3ae7e5fa3f68/src/main/java/de/melanx/morevanillalib/api/RepairMaterialsList.java#L10

This class, if loaded too early, causes an impossible to catch exception, since it fails to load the class.  My code is prepared to handle the ingredient not being ready or essentially any other error from attempting to access the repair material, but this is a flaw in their code that cannot be handled by me.

**Comment by Bass2style** [comment]
okay, thanks for your rapidity. i'm reporting that on their git with linking this than.
