### ISSUE TITLE
[1.16.3][forge]conflict with Forbidden & Arcanus to load Jei on server

### ISSUE THREAD

**Issue by Prophious** [Shadows-of-Fire/Apotheosis#233]
link to JEI issue https://github.com/mezz/JustEnoughItems/issues/2101

it seems that while both Apotheosis and Forbidden & Arcanus(with library mod) and JEI are installed JEI has trouble loading first time on a server, usually requiring a relog or starting in single player first then able to play on server with JEI just normally

have tested with minimum mods, where both Apotheosis and Forbidden & Arcanus can have JEI work individually together Jei does not work first time 

mirrored https://github.com/stal111/Forbidden-Arcanus/issues/104

**Comment by Shadows-of-Fire** [comment]
This is likely due to this startup crash as visible in one of the logs you provided on the JEI issue: https://paste.ee/p/btAaf#s=0&l=2557
This is going to be something on F&A's end, as this is really not how you should be determining enchanting power on blocks, and it should be available before runtime (as it is with all vanilla blocks).

**Comment by Shadows-of-Fire** [comment]
Actually even more confusing, that's coming out of their getStateForPlacement, which should be a code level feature, and not determined by tags either.  Honestly with the way their code is written, you can break their mod very easily with a datapack that adds anything to those tags.
