### ISSUE TITLE
[1.16.1] Bug with the spawner module.

### ISSUE THREAD

**Issue by Khytwel** [Shadows-of-Fire/Apotheosis#241]
Hi!

There is a bug in the spawner module. When a mob is blacklisted, we can still add it to the spawner using shift + right click. This does not happen with just a right click.

Version: 1.16.1-4.1.3 (it also does it on version 1.16.3).

**Comment by Shadows-of-Fire** [comment]
So that commit fixes that issue, but upon further inspection, this issue is actually caused by a regression in how the RightClickBlock event works (the ALLOW result no longer does anything), so my previous event handler that fixed this behavior is just broken.

I'll be opening a forge PR to hopefully get this resolved properly.
