### ISSUE TITLE
confused about enchanting and trying to get certain enchants

### ISSUE THREAD

**Issue by DoomSquirter** [Shadows-of-Fire/Apotheosis#246]
playing po3 latest, Apotheosis-1.12.2-1.12.5

made a enchanting table + 16 hellshelves, 2 4.0 hellshelves (have the +X enchant on each) and 2 normal bookshelves.  

while I was getting up to this point, I was getting various enchants either on armor or weapon tomes, but once I added the 4.0 shelves, I seem to be getting the same enchants on every piece of armor I throw in there.

I'm trying to get mending and really that's all I want atm.  lol  but I don't know if it's on the lower end of the levels of where that enchant is or I've yet to get a high enough power level to reach it.

is there a way to see the enchants and what optimal level to get the item is?

**Comment by DoomSquirter** [comment]
second question but parallel to last.  is this the intended approach you need to do?  do you have to manipulate the bookshelves/power level to try to get the enchants you are after?

**Comment by DoomSquirter** [comment]
crap, just noticed that mending isn't gettable by enchanting table, which probably is my problem.

but rest of questions still stand.  sorta confused as to how to get certain enchants and if you have to play around with bookshelves to target them, etc.

**Comment by Shadows-of-Fire** [comment]
Apologies for completely missing this, questions are better handled by discord because it usually gets a more immediate response; anyhow:

When you hit a certain point, theres a chance you go past where certain enchantments are obtainable, every enchantment has a minimum and maximum enchantment power as a function of that enchantment's level.  There's no good way to look up this information for every enchantment, so it's kinda up to randomness to figure it out.

For the apoth enchantments, there was a document somewhere that had the enchanting power formulas listed on it, but it's a bit dated (it might still be up to date for 1.12, but eh) https://gist.github.com/Shadows-of-Fire/adab31e668b4fe71578bae2d5f87ee2b
