### ISSUE TITLE
Mixin Crash w/ Charm

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#281]
[`Charm Reforged v2.2.1`](https://www.curseforge.com/minecraft/mc-mods/charm-reforged) 
`Apotheosis v4.4.1`
`Minecraft v1.16.4`
`Forge v35.1.15`

- The mod crashes on launch when Charm Reforged is installed.

[Crash Report](https://gist.github.com/WenXin20/003231b7bae4fe67a7898202822ac1d5)
svenhjol/CharmForge#2

**Comment by Shadows-of-Fire** [comment]
Thats an incompatibility, the target of the mixin is no longer there due to apoth replacing it with a hook to allow apoth's enchant level features to function.

Any fix would probanly have to come out of charm, or maybe even mixin, not sure if a silent fail is possible, but there's nothing I can do about it, I don't think.

**Comment by WenXin20** [comment]
Alright, thanks
