### ISSUE TITLE
[Question] Combining Affix Loot Properties

### ISSUE THREAD

**Issue by LightningCobra** [Shadows-of-Fire/Apotheosis#292]
My friends and I recently booted up a server with a small modpack, including apotheosis. I really liked the cool properties of the affix loot, particularly on the armour. However, I thought it'd be really nice if there was a way to combine the properties together. Maybe we've all missed it, but we haven't been able to find anything. If you don't want to change the mod (understandably) could you point out the location in the code so that we could possibly change it ourselves? Thanks!

**Comment by Shadows-of-Fire** [comment]
Right now affixes can only be manipulated using raw nbt editing, so that's the only method of doing that.  You would just need to kinds gather the nbt tags for the affixes you want and manually craft the nbt and apply it ti an item.

Forge has recently added a new feature that should allow me to make this less painful, but it will break existing affix items to start using.
