### ISSUE TITLE
Sugar Cane can be planted in water

### ISSUE THREAD

**Issue by Rafii2198** [Shadows-of-Fire/Apotheosis#311]
# Game info
Minecraft: 1.16.4
Forge: 35.1.36
Apotheosis: 4.4.1
# The bug
Apotheosis' Sugar Cane from Garden module can be planted in water and grow, something that is impossible to do in Vanilla as water destroys sugar cane. Note that it only grows when there is air above it so planting one sugar cane underwater is basically pointless.
# Idea
This is a bug that should occur but that gave me an idea that maybe it would be cool if Garden module added some kind of craft able "Supported" plants like Supported Sugar Cane, it could be planted underwater but only grow normal version of the plant. It would also count as normal plant in terms of grow hight like if you have sugar cane hight set to 5 and plant 2 supported version then only 3 sugar cane could grow out of it.

# Screenshot
![image](https://user-images.githubusercontent.com/26695327/106358923-6c71f900-630f-11eb-8555-209ae8c7e136.png)

**Comment by Cryomancer765** [comment]
That's not a bug, that's vanilla behavior, the sugar cane sees valid placement since the block it's on is adjacent to water. The water views the sugarcane as a block so it doesn't flow into it.

![2021-02-08_17 51 46](https://user-images.githubusercontent.com/12061270/107296454-084de400-6a37-11eb-92e2-132f42e8b4c0.png)
