### ISSUE TITLE
Ticking block entity: ApothSpawnerTile

### ISSUE THREAD

**Issue by Smurfz87** [Shadows-of-Fire/Apotheosis#391]
Been getting several crashes similar to the attached crash report:

[crash-ApothSpawnerTile-204.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6548897/crash-ApothSpawnerTile-204.txt)

Playing the Mineshafts & Monsters pack, so there's a decent amount of mods, however the stacktrace only features Apotheosis so hope this belongs here. Let me know if you need any further information 🙂

**Comment by Shadows-of-Fire** [comment]
This is - unfortunately - a CME, which means some other mod in your instance is doing the same thing the spawner is doing (adding an entity to the world or otherwise modifying the world entity list) off of the main thread.  It's practically impossible to trace though, but this is nothing fixable on my end.
