### ISSUE TITLE
Cant Joint Server

### ISSUE THREAD

**Issue by Deathawaits4** [Shadows-of-Fire/Apotheosis#405]
With this mod installed and the newest forge version i can not longer join the server. I keep getting the message: "Interal Exception: io.netty.handler.codec.DecoderException: Java.lang.IndexOutOfBoundsException: Index: 25, Size: 5

This is 100% only with this mod installed and no other. The server starts without issues and single player also works without issues. I also dont get any logs.

**Comment by Shadows-of-Fire** [comment]
Provide debug logs from both client and server

**Comment by NoticeRL** [comment]
I'm having the same issue, gives me hope that it can be solved though because I also have apotheosis in my modpack. 
Speculation from many things seems to point to that it COULD be a username length issue, but mine is already extremely short and I made it shorter and it didn't change anything. 

I don't know if I can get logs because as Deathawaits4 said, its not server side and I also don't get any logs. 

Would love to hear any ideas about this.

**Comment by InteJason** [comment]
same, the client log here: https://paste.ee/p/zLrTy

**Comment by IchigoGames** [comment]
Same issue i with my new pack but i have the same mod in another pack and no issue so im thinking its a mod compatibility issue
that or a issue with forge 36.1.32 1.16.5

**Comment by Shadows-of-Fire** [comment]
Someone else reported a similar issue occuring when Scaling Health was installed

**Comment by InteJason** [comment]
I don't have scaling health installed. But the issue still exists.

**Comment by Shadows-of-Fire** [comment]
Apoth's development end has been updated to Forge 36.1.65.  I am able to connect to dedicated servers with Apoth, Placebo, JEI, and Jade installed with no issues.  Closing as non-reproducible.
