### ISSUE TITLE
Limited Enchantability

### ISSUE THREAD

**Issue by Apwalchan** [Shadows-of-Fire/Apotheosis#407]
ALL THE MODS 6 
Minecraft 1.16.5
curse forge
I have a bunch of hells shelves, trying to now enchant them with hell infusion, got a few but then it now only gives me all three spaces grayed out saying: limited enchantablity and wont let me do anything with it. how can I get past this? I'm over lvl 100 and it doesn't matter

**Comment by Shadows-of-Fire** [comment]
That message (terrible message, but it's what vanilla shows) means there are no enchantments available for the item you are trying to enchant at the specific enchanting power you have randomly achieved.

With hellshelves this is likely due to either your eterna not being high enough (it needs to be the max available) or a bad quanta roll (because quanta can cause your enchanting power to drop).

You either need a higher level, or you need to enchant something else to change your enchanting seed and try again.

**Comment by Apwalchan** [comment]
ah ok yeah i enchanted a different item and its working thanks idk why I didnt think of that I appreciate it
