### ISSUE TITLE
[Feature Request] Ignore Light levels

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/Apotheosis#423]
Would it be possible to get a config option so that apotheosis spawners ignore light levels. This would prevent people from being able to lightup spawners to disable them. Would be useful for some...things... I have in mind :P If not np I'll just do a minimod or something. Thanks!

**Comment by Shadows-of-Fire** [comment]
It doesn't really look like that kind of targeted condition ignorance is possible - it would require that the spawner somehow lie to the world to make the block look like it had a light level of zero (which would be really involved, since you cannot arbitrarily set light levels).

You can't really even trick the thing to ignore light in particular, since the conditionals that handle checking are just method references, and are (entity, world, pos, type) -> bool [so all or nothing allowed to spawn or not], and each entity uses a different one)
