### ISSUE TITLE
Kikoku not respecting increased mod cap

### ISSUE THREAD

**Issue by braingkk** [Shadows-of-Fire/Apotheosis#48]
apotheosis increases the cap of several enchants well beyond vanilla, making unbreaking up to 80, sharpness 15 etc. while the kikoku is generally used to double enchantment cap, it does not work well with apotheosis, even dropping some applied enchants to standard cap.

unsure if the inability to double that is intended or not, and if it is even the fault of this mod or the other, so cross posting.

https://github.com/rwtema/Extra-Utilities-2-Source/issues/320

**Comment by Shadows-of-Fire** [comment]
Extra utilities does some weird hacky stuff, and I don't think I can do anything to support it.

That said, it will probably never be able to double up the new cap, since that system is applied externally into the enchanting mechanics (anvil + table), and I think the kikoku uses some weird event handlers to manipulate itself.

**Comment by braingkk** [comment]
fair enough, thanks anyway.
hopefully XU has the interest and ability to make some hook for other mods to change the base caps that are doubled
