### ISSUE TITLE
Server crashing due to 'Exception ticking world'

### ISSUE THREAD

**Issue by ron4821** [Shadows-of-Fire/Apotheosis#491]
Hello, my server just crashed with the following log.  

I couldn't determine what was causing the issue, but I saw apotheosis mentioned a ton.  Wondering if this issue is with the mod?

Thanks for the help

[crash-2021-12-09_22.59.09-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7689038/crash-2021-12-09_22.59.09-server.txt)
!

**Comment by Shadows-of-Fire** [comment]
This is the same crash as in #490 
However, for this to happen, a crash would have happened earlier

Since the call trace requires the passed-in entity to be a `MobEntity` and a `PigEntity` is an `AnimalEntity`.

I suspect there is some other mod doing something weird.  There's not really anything I can do from my end.
