### ISSUE TITLE
[1.18.1] "invalid player data" when creating a new world.

### ISSUE THREAD

**Issue by Bass2style** [Shadows-of-Fire/Apotheosis#514]
Hi,

like the title indicates, whe i create a new world, i can't join and get a "invalid player data".

i can't publish the full latest.log on gist, but here is the, i think, most important part of it : https://gist.github.com/Bass2style/3bd02ca402aebea1acfc028a53be1828

have a nice day.

edit : not sure it's usefull, but here is the modlist of the modpack : https://gist.github.com/Bass2style/1ecb46e2d26251ba8eb16401ad391e62

**Comment by Shadows-of-Fire** [comment]
This is due to me missing a null check at https://github.com/Shadows-of-Fire/Apotheosis/blob/ada49e1ac5aa85ab8353a5747cfd784877eba132/src/main/java/shadows/apotheosis/ench/EnchModuleEvents.java#L109

That was *caused* because there is a missing `@Nullable` annotation on the `LootingLevelEvent`  as noted in https://github.com/MinecraftForge/MinecraftForge/issues/7714
This should be quick fix, luckily.
