### ISSUE TITLE
Missing textures on Anvils, Cactus and Sugarcane

### ISSUE THREAD

**Issue by Asf4lis** [Shadows-of-Fire/Apotheosis#558]
![2022-04-22_21 27 27](https://user-images.githubusercontent.com/104204056/164706625-87a95301-ccf0-4e69-83fe-72ab4b4fabd1.png)
Anvils, cactus and sugarcane most of the time are missing their textures. Sometimes logging fixes this, and sometimes dying will cause it.

**Comment by Glowing0v3rlord** [comment]
Can you post a list of the mods you have installed? This doesn't sound like an Apotheosis issue.

**Comment by Shadows-of-Fire** [comment]
This is typically caused by either
* Only having the mod installed on the client, when playing on a server where the mod is not present, which is not supported behavior
* Installing the mod into an existing world, where the fix is to break/replace these blocks, though I believe that should not be necessary anymore past 1.12...
* Registry Corruption, which is an external problem.

This sort of weirdness is a drawback of registry-replacement, but it is a supported forge feature and it does work properly in isolation (and in large environments, as there have been no such issues in E6, E8, ATM6, or ATM7).

**Comment by Asf4lis** [comment]
Yup, found out the server owner hadn't updated the mod to the newest version so we sorted it quickly - since those three things are all effected by apotheosis I knew it was involved but the issue is now sorted - cheers gang!
