### ISSUE TITLE
Knowledge of the Ages low XP count

### ISSUE THREAD

**Issue by Nyntex** [Shadows-of-Fire/Apotheosis#569]
So, usuallly Knowledge of the Ages should give you 25 * level experience points per item converted. I was killing literally hundreds of creepers using spawners (and yes I know creppers are not the best for this) but it took ages with looting 8 and KotA 4 to get from lvl 54 to 55. From what i've seen it should take like 1-2 Creeper for a level up since I only need 300xp for this level up. So I feel like something is messed up with the calculation. Also I haven't seen this issue posted before

Apotheosis-1.18.2-5.3.5

Forge 40.1.20

**Comment by Shadows-of-Fire** [comment]
KotA's code and formula has barely (if at all) been changed since 1.16, that code is visible here https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/ench/enchantments/masterwork/KnowledgeEnchant.java#L42

The amount of raw experience needed at that level is extremely high, because of the exponential scaling. I cannot currently check what the number is, but its certainly more than 300.

**Comment by Nyntex** [comment]
the code looks good to me, for someone who has never programmed in java and has barely any competence using C#. To the Amount of XP, the calculation for the xp need to level up is  9[level]-158 (this is for lvl 32 and beyond). With level 54 i need 328 xp to level up. I will check if there is something else messing with the xp drops because this is really not normal. Thank you for the answer though

**Comment by Nyntex** [comment]
Alright, I found out that Apotheosis is not the problem. The actual problem was the Mod Clumps that didn`t put the experience orbs together correctly, so yea, my problem is solved
