### ISSUE TITLE
Charm refresh lets it get to zero

### ISSUE THREAD

**Issue by smilodon79** [Shadows-of-Fire/Apotheosis#615]
Right now, the charms count down to zero and then refresh the timer.  As a result, the potion effect wears off completely for a second or so, before it's reapplied.  This has two major issues:

1.  Night vision flickers for 15 seconds before turning off completely and then gets reapplied, making the game unplayable.
2. Potion effect going off impacts gameplay (if the potion effect is of fire resistance, and we're caught in lava for instance).

Recommended solution:  If the potion effect is applied for 30 seconds, refresh it every 10 seconds to avoid potion flickering and other issues.

Game Version:  1.16.5
Mod Version:  1.16.5-4.8.99F

**Comment by Shadows-of-Fire** [comment]
I'll be honest none of what you're saying is correct - the charms do not allow the effect to expire (they refresh at 5 ticks) and night vision refreshes even earlier due to the flickering.  The code is visible here https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/potion/PotionCharmItem.java#L51
