### ISSUE TITLE
Infinite boss spawning in the nether?

### ISSUE THREAD

**Issue by set92** [Shadows-of-Fire/Apotheosis#642]
I'm playing ATM 7, and a couple of days ago I upgraded the modpack from 0.4.24 to 0.4.29. Technically, it doesn't affect apotheosis, and I think I entered the nether after that, but is the only thing outside the game that happened. So, basically, I just entered to the nether and there is a constant stream of boss announcements with its annoying sound.

Not sure if I can do something else to debug it, or to turn it off. In the overworld it was day if it matters for something (mentioning since in the overworld the boss announcements only appear at night, I suppose this is normal, although I got like 3 or 4 announcements pretty quick too)

PS: All this was without moving.

**Comment by JustinCarrotCake** [comment]
Affix bosses spawn as a player moves through the world and cause hostile mobs to spawn. I've noticed this in the End dimension as well, flying between islands, once a boss despawns behind me another one or two will spawn in the direction I am heading.

In the Nether, with it being a void, the only place for mobs to spawn is on top of Nether fortress blocks. Thus, when you are killing mobs or loading new chunks, large amounts of hostile mobs are spawning in a short period of time between despawning behind you and generating in the chunks you're traveling to. Traveling to the Nether loaded a large amount of chunks simultaneously; I'd imagine the flood of boss announcements were all the bosses spawning in at once.

Just adding context. It's possible there was an un/intentional tweak somewhere that affected the chance of apotheosis bosses spawning when a hostile mob spawns in to the world.

**Comment by Shadows-of-Fire** [comment]
The trigger for bosses has been updated in 5.7.0, and there is required delay between boss spawns, which should reduce the spam.
