### ISSUE TITLE
[Bug] 5.7 Apotheosis, enchantment table causing a crash

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/Apotheosis#675]
User claims it crashed when placing some items in it, I've had other players report this crash as well when putting none books into it, like trying to put an enchanted sword into it etc. 

[crash-2022-10-14_23.00.50-client.txt](https://github.com/FTBTeam/FTB-Modpack-Issues/files/9789718/crash-2022-10-14_23.00.50-
client.txt)

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1438

**Comment by Shadows-of-Fire** [comment]
Unfortunately that crash isn't something I can actually guard against - some enchantment has a null enchantment category which is not a valid behavior, but the crash report is not informative.

Since it goes down to a vanilla code path I can't actually inspect the enchantment at this stage either.  You would need a mod that runs checks such that registered enchantments are actually valid.
