### ISSUE TITLE
BUG: Dropping an anvil on gems on a lower half slab destroys the gem and no dust appears

### ISSUE THREAD

**Issue by VallenFrostweaver** [Shadows-of-Fire/Apotheosis#681]
Minecraft 1.18.2
Forge 40.1.80
Apotheosis 5.7.0

Placed a half slab down. Tossed gem on top. Placed anvil a few blocks above it. Anvil falls down on gem and half slab & the anvil turns into a dropped item but the gem is deleted and no dust drops from the gem.

**Comment by Shadows-of-Fire** [comment]
Does the anvil pop off in this scenario (instead of landing)?

**Comment by VallenFrostweaver** [comment]
Yes it does.

**Comment by Shadows-of-Fire** [comment]
So this is an interesting issue with a bit of compound issues going on:
1) An anvil "popping" should not crush a gem - this is working as intended
2) Apparently, anvils _can_ deal damage to item entities, killing (deleting) them in the process.
3) The above damage is basically up to randomness, because it requires that the entities AABB's intersect during the fall.

However, since the smashing of gems with anvils is going to be an intended process, I will need to mark them as invulnerable to anvil damage.
