### ISSUE TITLE
Affixes failing to generate

### ISSUE THREAD

**Issue by miltonniklasson** [Shadows-of-Fire/Apotheosis#682]
I'm getting errors in the server console every now and then looking like this: 21.10 22:58:40 [Server] Server thread/ERROR [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_chestplate/rare/EFFECT/0.33!. They come in intervals but with different items failing each time.

**Comment by tachometer74** [comment]
Having the same issue here - 1.18.2-5.7.2

If you want logs, files, whatever...let me know, happy to help.

**Comment by Shadows-of-Fire** [comment]
fixed in 5.7.3

**Comment by ghost** [comment]
> 

still there.. with v6.0.0

**Comment by Shadows-of-Fire** [comment]
6.0.0 is outdated.

**Comment by DarkSolus** [comment]
Reopening the issue due to it occurring in my server as well.
Apotheosis version 7.0.5, MC 1.20.1

`[23Oct2023 18:52:09.315] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:52:54.188] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:53:44.054] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:54:08.901] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:55:35.036] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:55:55.001] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:02.458] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:05.156] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:13.191] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:30.903] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/apotheosis:mythic/ABILITY/0.3!`

This happened in the End, all loot as a result rolled without any affixes, just vanilla enchants.

During server startup these messages also show up, but I haven't been able to figure out how to fix them.

`[23Oct2023 14:02:06.681] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category helmetRequired: 3; Provided: 2`
`[23Oct2023 14:02:06.681] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2`
`[23Oct2023 14:02:06.685] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bowRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.685] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category crossbowRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.686] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category pickaxeRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.686] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shovelRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.687] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.688] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 2`
`[23Oct2023 14:02:06.688] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2`

**Comment by djcprone** [comment]
> Reopening the issue due to it occurring in my server as well. Apotheosis version 7.0.5, MC 1.20.1
> 
> `[23Oct2023 18:52:09.315] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_helmet/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:52:54.188] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:53:44.054] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:54:08.901] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:55:35.036] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:55:55.001] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_helmet/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:56:02.458] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:56:05.156] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:56:13.191] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_boots/apotheosis:mythic/ABILITY/0.3!` `[23Oct2023 18:56:30.903] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/apotheosis:mythic/ABILITY/0.3!`
> 
> This happened in the End, all loot as a result rolled without any affixes, just vanilla enchants.
> 
> During server startup these messages also show up, but I haven't been able to figure out how to fix them.
> 
> `[23Oct2023 14:02:06.681] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category helmetRequired: 3; Provided: 2` `[23Oct2023 14:02:06.681] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2` `[23Oct2023 14:02:06.685] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bowRequired: 5; Provided: 4` `[23Oct2023 14:02:06.685] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category crossbowRequired: 5; Provided: 4` `[23Oct2023 14:02:06.686] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category pickaxeRequired: 5; Provided: 4` `[23Oct2023 14:02:06.686] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shovelRequired: 5; Provided: 4` `[23Oct2023 14:02:06.687] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4` `[23Oct2023 14:02:06.688] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 2` `[23Oct2023 14:02:06.688] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2`

+ 1 to this. Version 7.0.5 on MC 1.20.1, forge 47.1.3

**Comment by Louie365** [comment]
This is causing people to crash in my server when getting close to the Iron's spellbook spells items when dropped on the floor.
Any ideas?

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[INFO] .... [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@2c03d69c[id=<null>,name=Louie365,properties={},legacy=false] (/94.155.24.41:58890) lost connection: Disconnected

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[INFO] .... [minecraft/ServerLoginPacketListenerImpl]: UUID of player Machi1503 is 50e21463-60d9-4c51-a0be-b6fc6c5aacc2

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/0.33!

**Comment by Shadows-of-Fire** [comment]
It is the responsibility of the loot category owner to ensure there are ample affixes - iron's spells, in this case.
