### ISSUE TITLE
[1.19.2] Crash when adventure module is disabled

### ISSUE THREAD

**Issue by RatchetG95** [Shadows-of-Fire/Apotheosis#688]
Apotheosis-1.19.2-6.0.1

Cant load or create a new world with the adventure module disabled. When i try this shows up: 
![javaw_2022-10-24_21-46-01](https://user-images.githubusercontent.com/12844367/197613092-2a301050-693e-46aa-8daa-4a4358482c06.png)

Apotheosis and its dependencies are the only mods installed

**Comment by Shadows-of-Fire** [comment]
You will need to provide a game log.  This issue is not reproducible with Placebo 7.0.1 and Apotheosis 6.0.1

**Comment by RatchetG95** [comment]
https://pastebin.com/3nCeM4K2

There you have the log

**Comment by Shadows-of-Fire** [comment]
I cannot reproduce this issue with the mods you have loaded.

Forge 43.1.47
Apoth 6.0.1 
Placebo 7.0.1
Patchouli 77
Ench Desc 13.0.3
Bookshelf 16.1.5

Worlds load fine, and the error present in your log is not showing.  All jars were pulled from curseforge.

**Comment by RatchetG95** [comment]
I tried it on my laptop and got the same problem. Here's the log
https://pastebin.com/p4puncH3

**Comment by NeinAbgelehnt** [comment]
I had (almost) the same issue if i disable some modules in the apotheosis config file... I set in the config file the adventure and deadly module to false and i can't load or create a world.
If I load a world i get this error message: _Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode") or go back to the title screen to manually fix it_

This happens when i create a new world:
https://pastebin.com/LiD4xUkt

Apotheosis-1.19.2-6.0.1
Patchouli-1.19.2-77
Placebo-1.19.2-7.0.1
Forge 1.19.2 43.1.47

**Comment by Shadows-of-Fire** [comment]
Ah, the module thing might explain that.

**Comment by Shadows-of-Fire** [comment]
Changes are needed in Forge for me to properly fix this issue - awaiting https://github.com/MinecraftForge/MinecraftForge/pull/9113

**Comment by SharkBairRFSR** [comment]
so other than the config there's no way to remove the modules?
