### ISSUE TITLE
Request: Affix Item Tag, Sorting, Salvaging Table Auto/Pipeing

### ISSUE THREAD

**Issue by sojakai** [Shadows-of-Fire/Apotheosis#701]
Playing "All the Mods 7: To the Sky", which has Apotheosis in it. I have noticed that Upgrading Mob Spawners causes a problem with sorting items because of the Affixes added to Drops not Stacking. Example: Sticks (Vanilla) vs any Stick with an Affix on it. Witches drop Sticks and Hats which both get affixes and instead of being a single stackable item, Turns into HUNDREDS of Items each with different combos of affixes. This causes slowdowns in FPS because of the number of items being dealt with, and rapidly destroys AE/RS systems, not to mention Storage Draws/Functional Storage or Chests.

Please add something Targetable to the NBT/Item that allows them to sort out the Affix items. 

The Salvaging Table is ok, but needs a way to pipe in/out of it. I can handle manually pushing the button (would love an auto salvager (upgrade machine?)) to make it work, but want to pipe items in/out of it so I can push the button to break down whats in it, and it gets restocked by pipe in and the broken down items get piped out for use in the Reforging Table/storage drawers.

I love using Apoth for Farms, but the Affixes are getting very... troublesome.

**Comment by Shadows-of-Fire** [comment]
Sticks having affixes is a modpack problem, not an Apoth problem (this means they didn't reset the config after 5.7.0 as noted in the changelog).

Also, affix items always have had special nbt data on them (that's where they store the affixes), under the subkey `affix_data`.  If you have nbt filtering you can check if that nbt tag exists.

The salvaging table is manual since the acquisition of affix items is not supposed to be so massive.  That, again, is a modpack-level issue if there are so many of them spawning.  A modpack could also add machine recipes for bulk salvaging if they so desired.

**Comment by sojakai** [comment]
Thank you for telling me about the config issue. I will see about rectifying it on my end. Now to respawn the cfg file.
