### ISSUE TITLE
[1.19.2] Apotheosis Bosses Spawn in "no-hostile" biomes

### ISSUE THREAD

**Issue by Jimsmithing** [Shadows-of-Fire/Apotheosis#787]
Using version 6.0.1, it appears that bosses spawn on Mushroom Islands. Checked the changelogs for future version and didn't see a change for this particular issue. A biome blacklist in addition to a dimension blacklist would be nice.

**Comment by Shadows-of-Fire** [comment]
Can't reproduce.  Boss spawns utilize the `SpecialSpawn` event as a trigger (with a natural spawn source), which fires only on successful mob spawns.  Since mobs don't spawn in the mushroom fields by default, this effectively prevents boss spawns.  If you have normal mobs spawning there for some reason, then bosses could spawn, but something else would have to be enabling spawns there first.
