### ISSUE TITLE
Crashed while hovering over affix item.

### ISSUE THREAD

**Issue by BiakCeu** [Shadows-of-Fire/Apotheosis#812]
Hovering over my item that was reforged with an older version of apotheosis, I forgot which older version as I immediately deleted it while updating to the latest. 
Apotheosis-6.1.2
Placebo-1.19.2-7.1.5
Forge version 43.2.6

To reproduce it, all I did was hover over the item then instant crash.

CRASH REPORT- https://pastebin.com/kri7mtCa

**Comment by Shadows-of-Fire** [comment]
Hovering the item is not the cause of the crash report shown - the shown report lists the crash that happens if an affix item attempts to generate yet has no valid affixes to choose from.

However, such an error indicates poor modification of affixes via datapacks, as that is the only way to remove affixes, and there are always enough by default. If you have any datapacks, disable them and try again.

If you think the issue is a tooltip issue (as stated), then try to find a crash report which describes such an issue.

**Comment by BiakCeu** [comment]
Alright, I just removed the whole thing. I only got it because I assumed the datapack is what changed the chances of getting gems in chests, which was really high for my liking, only to find out it didn't really change what I wanted. Thank you!
