### ISSUE TITLE
Arrow velocity on Trident doesn't make sense

### ISSUE THREAD

**Issue by Twisted-Code** [Shadows-of-Fire/Apotheosis#849]
The way I interpret this is one of the following:

- it literally means arrows, in which case it doesn't make sense for a trident to be able to have it, and you should double check for other invalid enchantments(/affixes).
- it actually means projectile velocity, in which case the string should be clarified for this and similar enchantments(/affixes).
As it stands I'm not sure which it is, since it's pretty difficult (though I suppose not impossible) to measure the comparative speed of a projectile, especially if you're the one firing it. 
![image](https://user-images.githubusercontent.com/7110033/230902248-bc82aa0a-032f-4ba3-8720-0cf1940c0728.png)

**Comment by rtxyd** [comment]
Speed influence the damage.

**Comment by Shadows-of-Fire** [comment]
This only makes sense if you know that internally a `ThrownTrident` entity is an extension of `AbstractArrow`.

It would be a misnomer to label Arrow Velocity as Projectile Velocity because it does not work for all projectiles, only arrows, but there isn't really a great way to display to the player that the trident is actually an arrow (internally, anyway).

I think the fact that the range stats can show up on the trident are sufficient enough to convey that they work, and don't have any better solutions, so I'm going to leave it as-is.

**Comment by Twisted-Code** [comment]
Oh, yeah, that is a bit of a predicament. The only thing I can think of is changing both the tooltip string AND the affix's logic to affect all projectiles (whatever abstract class is behind things like guest fireballs and ender pearls) but making it too general could cause other problems. Perhaps, in lieu of a direct solution, you could add a bit of clarification to the documentation somewhere, e.g. affixes.txt, that "yes, arrow modifiers affect tridents"?
/shrug
