### ISSUE TITLE
(1.19.2) Piercing on Tridents only hits up to 2 targets

### ISSUE THREAD

**Issue by SillyGoblin** [Shadows-of-Fire/Apotheosis#851]
I came across an issue where no matter how clumped a group of monsters are and no matter how high the Piercing enchantment is the trident doesn't seem to damage more than 2 targets. I don't know if that's intentional, but I assumed every level past 1 would increase the amount of targets hit by the projectile, just like with crossbows.

versions used is
Forge 43.2.3
Apotheosis 6.1.5
Placebo 7.1.7

the steps I used to reproduce this is enchanting a Trident with Piercing greater than 1, then test the trident on a 3 by 3, 2 block deep pit filled densely with creepers.

**Comment by Shadows-of-Fire** [comment]
What is happening here is that due to how tridents track if they have hit an entity (for purposes of returning with the Loyalty enchantment), they cannot hit more than one entity in a given tick.  This means that clusters of enemies will not be pierced correctly, but a spread-out chain of enemies will work properly.

I'll explore how to keep the flag set to false.  I already reset it at the end of `onHitEntity` but clearly that isn't good enough.
