### ISSUE TITLE
World Crash - Failed to locate any affixes

### ISSUE THREAD

**Issue by Wubzzz1337** [Shadows-of-Fire/Apotheosis#855]
Can't figure out what causes it, if I disable the "Adventure" settings in this mod it does not crash anymore, so something with Looting is making issues or maybe another mod.

Minecraft 1.19.2
Forge: 43.2.8
Latest version of Apotheosis on 1.19.2

Crashlog: 

[crash-2023-04-15_10.34.57-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11238909/crash-2023-04-15_10.34.57-server.txt)

**Comment by rtxyd** [comment]
Reproduce the crash with 4 mods, which is caused by wrong datapack.
It seems you override the datapack with a version that dosn't define "common" rarity "helmet" in the affixes namespace.
Here is the crash-reports, I suggest you check the datapack you are loading, or delete it use the default datapack.

[crash-2023-04-16_05.34.34-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11240711/crash-2023-04-16_05.34.34-client.txt)

**Comment by Shadows-of-Fire** [comment]
This crash means you disabled enough affixes that there are none available for a particular rarity/category combo.  You are responsible for not breaking your environment.
