### ISSUE TITLE
[1.19.2-6.3.0] Unbreakable charm recipe not working at max allowed Arcana value 

### ISSUE THREAD

**Issue by LuciusV** [Shadows-of-Fire/Apotheosis#953]
Draconic Endshelf: 3
Pearlescent Endshelf: 5
Melonshelf: 4

Stats: Eterna 50/50, Quanta 12.50% , Arcana 37.50%  OK - exactly upper limit but no more than it)
Result: Infusion not available
Expected result: Infusion available (Arcana at least 32.5, no more than 37.5: **its no more** but equal).
Please fix check for value range at edge

**Comment by Shadows-of-Fire** [comment]
This is because of the enchantability bonus from the charm itself (every item is providing a base value of 1 due to a global change).

I've reduced it back to zero for the charm. I may undo this change entirely in the future, as it is also what allows every item to receive Soulbound when a mod that adds it is present.
