### ISSUE TITLE
[Clarification] Datapacks

### ISSUE THREAD

**Issue by Jophire** [Shadows-of-Fire/Apotheosis#968]
Hello,
I have been working on making a datapack for various other mods attributes and was looking for some clarification on what 'steps' does inside the affixes data. 

Also a list of valid operation values.

Thank you.

`{
	"type": "apotheosis:attribute",
	"attribute": "feathers:feathers.feather_regen",
	"operation": "ADDITION",
	"values": {
		"common": {
			"min": 1,
			"steps": 2,
			"step": 1
		},
		"uncommon": {
			"min": 2,
			"steps": 2,
			"step": 1
		},
		"rare": {
			"min": 3,
			"steps": 3,
			"step": 1
		},
		"epic": {
			"min": 4,
			"steps": 5,
			"step": 1
		},
		"mythic": {
			"min": 5,
			"steps": 5,
			"step": 1
		},
		"ancient": {
			"min": 6,
			"steps": 8,
			"step": 1
		}
	},
	"types": [
		"helmet", "chestplate", "leggings", "boots"
	]
}`

**Comment by Shadows-of-Fire** [comment]
These refer to the actual value of the affixes, for the following:
```json
{
    "min": 10,
    "steps":  10,
    "step": 1
}
```
The affix would have a min value of 10, but a max value of `min` + `steps` * `step` = 10 + (10 * 1) = 20

This is used instead of a static min/max value so that only "clean" numbers are used, because that generates values like `12.14533`
