### ISSUE TITLE
[1.20.1] Apotheosis along with Sniffer Plus causes automatic step up

### ISSUE THREAD

**Issue by BugmanBugman** [Shadows-of-Fire/Apotheosis#982]
https://www.curseforge.com/minecraft/mc-mods/hellions-sniffer
Tested all my mods and played it with just these mods.

**Comment by Shadows-of-Fire** [comment]
This appears to be caused by the following mixin: https://github.com/Dariensg/Hellions-Sniffer-Plus/blob/1.20/Forge/src/main/java/com/helliongames/snifferplus/mixin/EntityMixin.java

I do not know what the purpose of this mixin is, because it is an override equal to the default implementation found here: https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java#L210

This conflicts with the way that Apothic Attributes changes step height here (AA removes uses of the legacy `maxUpStep` field and forces the attribute for players): https://github.com/Shadows-of-Fire/Apothic-Attributes/blob/1.20/src/main/java/dev/shadowsoffire/attributeslib/mixin/IForgeEntityMixin.java

The other mod needs to remove their mixin, or at the very least provide some justification for applying a mixin with the same contents as the original code.  Further discussion should probably be taken on https://github.com/Dariensg/Hellions-Sniffer-Plus/issues/10
