### ISSUE TITLE
Affix buffs not disappearing when armor is removed

### ISSUE THREAD

**Issue by executionByFork** [Shadows-of-Fire/Apotheosis#999]
I am running Minecraft v1.18.2 - Apotheosis v5.7.7

When I remove my step height +1 boots, I can still step up fences. Max health also remains when I remove all armor. Speed buffs seem to go away properly though, at least as far as I can tell by the FOV changing on equip/unequip.

Is this a known bug? Are there solutions? I know this is not the latest version of Apotheosis, but there is only one version newer on curseforge for 1.18.2, and I do not see anything in the changelog.md file hosted here about the changes that v5.8.1 brings. If it will fix this issue I'll happily try updating, but otherwise I want to avoid both the hassle of potential mod compat and new bugs, and the overhead of distributing a new modpack version to my players

**Comment by Shadows-of-Fire** [comment]
No clue, the mechanism that affixes use to apply and remove attribute changes is the same one vanilla uses for armor items (and the uuids are cached per-slot within the affix). The only thing that *might* cause issues in the 1.18 iteration of that subsystem is reloading at runtime, which may cause old affix instances to leak and thus the uuids to not match up.

The mechanism wasn't changed in 5.8, so updating is *unlikely* to fix it (though it might). 
Unfortunately I have no idea what the root cause is (as it could be a ton of things) and 1.18 is no longer supported.
